### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by jagz71** [jagz70/github-crash-course#1]
I think it looks better if the main tittle is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #e8d4b2;
}
```
